# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de09bcaa032367008ed2b0f8b3494e692fb8411584eaa23dd1227e15f781aaab05ea3c5b2fa2c66ef4d1b046c5feff8680dab0972e66e4fe4095e6ee7143c785

test:
  secret_key_base: e59bdb12ced02581133b95bdf318748bc5ca25631fe83e6b9881905bd9e7e0c79f0e402f8fe1e2982942ff9392d9e54e99d36715e0c71e916b28c1c1961d58b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
